### ISSUE TITLE
Please, install few linters , isort etc on your project

### ISSUE THREAD

**Issue by mserevko** [LaCost777/api-base-framework#2]
https://pypi.org/project/isort/
https://pypi.org/project/flake8/
https://dou.ua/forums/topic/32915/
https://pre-commit.com/

**Comment by LaCost777** [comment]
@mserevko 
Thank you foe the feedback, could you please review the pull request I've created to fix this issues? 
https://github.com/LaCost777/api-base-framework/pull/5

**Comment by LaCost777** [comment]
@mserevko
Thank you for the feedback, could you please review the pull request I've created to fix this issues?
https://github.com/LaCost777/api-base-framework/pull/5
